config/routes.rb
Rails.application.routes.draw do
  root to: 'contests#index'

  devise_for :users,
            only: [:sessions, :registrations, :passwords],
            controllers: { sessions: 'users/sessions' }

  resources :recruiters
  resources :contestants
  resources :schools
  resources :technologies
  resources :contests do
    resources :submissions
    resources :test_cases
  end

  resources :search, only: [:index]

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :recruiter
  belongs_to :technology

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 5 }
  validates :deadline, presence: true

  has_many :test_cases
  has_many :submissions

  include Searchable
  @searchable_fields = %w[title description]

  def max_points
    test_cases.count * TestCase::PASSED_TEST_CASE_POINTS
  end

  def to_s
    "\"#{title}\" by #{recruiter}"
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  acts_as_token_authentication_handler_for User

  before_action :validate_recruiter_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_contests,            only: [:new, :create]
  before_action :set_contest,             only: [:show, :edit, :update, :destroy]
  before_action :set_submissions,         only: [:show]
  before_action :set_submission,          only: [:show]
  before_action :validate_contest_author, only: [:edit, :update, :destroy]

  def index
    if current_user.recruiter?
      @contests = current_user.userable.contests.all
    else
      @contests = Contest.all
    end
  end

  def show
  end

  def new
    @contest = @contests.new
  end

  def create
    @contest = @contests.new contest_params

    if @contest.save
      respond_to do |format|
        format.html { redirect_to @contest }
        format.json { render @contest, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @contest.update_attributes contest_params
      respond_to do |format|
        format.html { redirect_to @contest }
        format.json { render @contest, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contest.destroy
    redirect_to contests_path
  end

  private

  def contest_params
    params.require(:contest).permit(:title, :description, :deadline, :technology_id)
  end

  def validate_contest_author
    if current_user != @contest.recruiter.user
      respond_to do |format|
        format.html { redirect_to @contest }
        format.json do
          render json: {
            errors: 'You should be the author of this contest in order to access this page'
          }
        end
      end
    end
  end

  def set_submissions
    @submissions = @contest.submissions
  end

  def set_submission
    @submission = @submissions.new
  end

  def set_contests
    # Here we are sure that the user is a recruiter
    @contests = current_user.userable.contests
  end

  def set_contest
    @contest = Contest.find_by id: params[:id]
  end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_body.html.erb
<%= render contests %>

app/views/contests/_contest.html.erb
<div class="card">
  <div class="card-title">
    <h3 class="heading"><%= contest.title %></h3>

    <span class="text-muted">
      <%= truncate(contest.description, length: 100) %>
    </span>
    <br>

    <%= render 'contests/contest_info', contest: contest %>
  </div>

  <%= link_to 'View contest info', contest, class: 'btn btn-default' %>
</div>

app/views/contests/_contest_info.html.erb
<div class="contest-info">
  <span>
    Company:
    <span class="font-weight-bold"><%= link_to contest.recruiter.company_name, contest.recruiter %>
  </span>
  <br />

  <span>
    Technology:
    <span class="font-weight-bold"><%= contest.technology.name %>
  </span>
  <br />

  <span>
    Max points:
    <span class="font-weight-bold"><%= contest.max_points %>
  </span>
  <br />

  <span>
    Application deadline ends in:
    <span class="text-info"><%= distance_of_time_in_words(Time.now, contest.deadline) %></span>
  </span>
</div>

app/views/contests/_form.html.erb
<div class="text-center form-wrapper">
  <%= form_for @contest do |f| %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
    <br />

    <%= f.text_area :description, class: 'form-control', placeholder: 'Description' %>
    <br />

    <%= f.label :technology %>
    <%= f.select :technology_id, options_from_collection_for_select(current_user.userable.technologies, :id, :name), {}, class: 'form-control'  %>
    <br />

    <%= f.label :deadline %>
    <%= f.date_field :deadline, class: 'form-control' %>

    <%= f.submit 'Create a contest', class: 'btn btn-default  form-control' %>
  <% end %>
</div>

app/views/contests/index.html.erb
<div class="text-center">
  <%= render 'body', contests: @contests %>
</div>

<% if current_user.recruiter? %>
  <%= link_to '+', new_contest_path, class: 'btn btn-lg btn-default btn-add btn-circle', data: { toggle: 'tooltip', placement: 'top' }, title: 'Add contest' %>
<% end %>

app/views/contests/new.html.erb
<div>
  <h1 class="text-center">Create a new contest</h1>
</div>

<%= render 'form' %>

app/views/contests/show.html.erb
<div class="form-wrapper text-center">
  <h1><%= @contest.title %></h1>
  <p><%= @contest.description %></p>

  <%= render 'contest_info', contest: @contest %>
  <br/>

  <%= link_to 'View submissions', contest_submissions_path(@contest), class: 'btn btn-default' %>

  <% if current_user == @contest.recruiter.user %>
    <br />
    <%= link_to 'Add new test case', new_contest_test_case_path(@contest), class: 'btn btn-success' %>
  <% end %>
</div>

<% if current_user.contestant? %>
  <%= render 'submissions/form' %>
<% end %>